# Generated by Django 2.0.6 on 2019-02-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('pageNumber', models.IntegerField()),
                ('publishDate', models.DateTimeField(default='')),
            ],
        ),
    ]
