# Generated by Django 2.0.6 on 2019-02-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default=''),
        ),
    ]
